### ISSUE TITLE
How can I use this on ES1.7.1, thanks

### ISSUE THREAD

**Issue by 0604hx** [spinscale/elasticsearch-suggest-plugin#38]

**Comment by spinscale** [comment]
you cant, please take a look at the [completion suggester](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-completion.html) instead, as well as this [introductory blog post](https://www.elastic.co/blog/you-complete-me)

**Comment by OOPMan** [comment]
Man, you'd think people would at least look at the most recent commit date before asking things like this?
